---
title: "R Notebook"
output: html_notebook
---

```{r}
library(jsonlite)
library(tidyverse)
library(shiny)
```

```{r}
all_nodups_df <- fromJSON("data/nodupsMail.json") %>%
  as.data.frame()

all_nodups_df$mailId

all_nodups_df %>%
  # pull(mailId) %>%
  tidyr::extract(mailId, "pdf_id", "(.*)_\\d{1,3}_\\d$") %>%
  pull(pdf_id) %>%
  unique()
```

```{r}
card <- function(subject, sender, recipient, date, body) {
        HTML(
            paste0(
                    '<div class="card">
                  <div class="container">
                  <h4><i>', subject, '</i></h4>
                  <hr>
                  <p>To: ', recipient, '</p>
                  <p>From: ', sender, '</p>
                  <p>Date: ', date, '</p>
                  <p>', body, '</p>
                  </div>
                  </div>')
                    )
}
```

```{r}
args <- lapply(1:4, function(.x) card(subject = all_nodups_df$subject,
                                              sender = all_nodups_df$from))

all_cards <- do.call(shiny::flowLayout, args)

all_cards[["children"]][[1]][["children"]][[1]]
```

```{r}
all_nodups_df %>% pull(subject)

lapply(all_nodups_df$subject, shiny::p)


# all_nodups_df %>%
#   mutate(
#     card_html = HTML(
#             paste0(
#                 '<div class="card">
#                   <div class="container">
#                   <h4><i>', subject, '</i></h4>
#                   <hr>
#                   <p>To: ', to, '</p>
#                   <p>From: ', from, '</p>
#                   <p>Date: ', date, '</p>
#                   <p>', body, '</p>
#                   </div>
#                   </div>')
#         )
#   )

all_nodups_df %>%
  rowwise() %>%
  mutate(
    test_html = div(h2(subject), p(body))
  )
```

```{r}
df_to_disp <- all_nodups_df

test_args <- apply(df_to_disp, 1, function(.x) card(subject = .x['subject'],
                                     sender = .x['from'],
                                     recipient = .x['to'],
                                     date = .x['date'],
                                     body = .x['body']))

test_args[1]
```




