name: rmv_emails
channels:
    - conda-forge
dependencies:
    - chardet>=3.0.4
    - ipython>=7.11.1
    - jupyter>=1.0.0
    - notebook>=6.0.1
    - pdfminer.six>=20181108
    - pandas>=0.25.3
    - Pillow>=6.2.1
    - pycryptodome>=3.9.4
    - six>=1.13.0
    - sortedcontainers>=2.1.0
    - tabulate>=0.8.6
    - unicodecsv>=0.14.1
    - fuzzywuzzy>=0.17.0
    - pip:
        - Wand>=0.5.8
        - pdfplumber>=0.5.14
