# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RMV Face Surveillance Emails
description: > # this means to ignore newlines until "baseurl:"
  NLP analysis of emails received from the Massachusetts RMV about facial surveillance
baseurl: "/rmv-face-surveillance-emails" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://https://aclu-of-massachusetts.gitlab.io/rmv-face-surveillance-emails/" # change this to the base hostname & protocol for your site
github-url: "https://github.com/ACLUmass/RMV-FaceSurveilance-Emails"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

# Make sure to exclude 'vendor' from the build
exclude: [vendor, "Gemfile", "Gemfile.lock"]
